 
version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  producer:
    build: ./producer  # Directorio del proyecto productor con su Dockerfile
    container_name: producer-service
    ports:
      - "8081:8080"  # Mapea el puerto 8080 interno a 8081 en la máquina host
    depends_on:
      - redis
    environment:
      - QUARKUS_REDIS_HOSTS=redis:6379

  consumer:
    build: ./consumer  # Directorio del proyecto consumidor con su Dockerfile
    container_name: consumer-service
    ports:
      - "8082:8080"  # Mapea el puerto 8080 interno a 8082 en la máquina host
    depends_on:
      - redis
    environment:
      - QUARKUS_REDIS_HOSTS=redis:6379
