

services:
  redis:
    image: redis:latest
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    container_name: producer_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_REDIS_HOST=redis
    depends_on:
      - redis

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    container_name: consumer_app
    restart: always
    ports:
      - "8081:8081"
    environment:
      - QUARKUS_REDIS_HOST=redis
    depends_on:
      - redis
      - producer

volumes:
  redis_data:
    driver: local

