version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  producer-api:
    build: .
    command: sh -c "uvicorn producer:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy

  consumer-api:
    build: .
    command: sh -c "uvicorn consumer:app --host 0.0.0.0 --port 8001 --reload"
    ports:
      - "8001:8001"
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis_data: