version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-broker
    ports:
      - "6379:6379"

  producer:
    build: ./producer
    container_name: python-producer
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "8000:8000"

  consumer:
    build: ./consumer
    container_name: python-consumer
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "8001:8001"
